name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan-ruby:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v5

      - name: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: scan-for-security-vulnerabilities
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v5

      - name: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: lint-code
        run: bin/rubocop -f github

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: install-packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: checkout-code
        uses: actions/checkout@v5

      - name: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: build-tailwind-css
        run: bin/rails tailwindcss:build

      - name: set-up-test-database
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: install-packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: checkout-code
        uses: actions/checkout@v5

      - name: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: build-tailwind-css
        run: bin/rails tailwindcss:build

      - name: run-tests
        env:
          RAILS_ENV: test
          # REDIS_URL: redis://localhost:6379/0
        run: bin/rails test:all

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout-code
        uses: actions/checkout@v5

      - name: log-in-to-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-and-push-docker-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
